version: '3.8'
services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      # IMPORTANTE: Ajuste para o seu fuso horário
      - GENERIC_TIMEZONE=America/Sao_Paulo

volumes:
  n8n_data:
